name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  base:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          # NOTE: install the latest node version
          node-version: '*'

      - name: Show versions and variables
        run: |
          node -v
          npm -v
          yarn -v

      - name: Set up configs
        # NOTE: https://github.com/dhis2/notes/issues/29#issue-421387830
        run: yarn config set network-timeout 100000 -g

      - name: Install
        run: |
          yarn
          yarn test:visual:install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Visual Regression Test
        run: yarn test:visual:ci

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: visual-regression
          path: .loki
